#!/bin/bash
MONITORS=$(xrandr --query | grep " connected" | cut -d" " -f1)
SYMBOLS="λ ⋚ ∞ Ẅ ω µ"

# kill existing progs
for prog in sxhkd compton polybar feh dunst; do
  pkill $prog
done

# start progs
sxhkd &
dunst &
~/dotfiles/scripts/battery_monitor.sh &
compton -O 0.5 -I 0.5 -b

# monitor set-up
for mon in $MONITORS; do
  MONITOR=$mon polybar --reload bottom &
  bspc monitor $mon -d ${SYMBOLS}
done

# mouse focus
bspc config focus_follows_pointer true
bspc config focused_border_color $(xrdb -query | grep ".cursorColor"  | cut -d $'\t' -f 2)

feh -z --bg-scale ~/dotfiles/wallpaper

bspc config border_width         2
bspc config window_gap          20
bspc config split_ratio          0.55
